### ISSUE TITLE
Output when there are no tests

### ISSUE THREAD

**Issue by vesln** [hydrojs/formatter#1]
It looks pretty cool actually. Just wondering if it's a good idea to tell the user no tests were executed?

![http://f.cl.ly/items/3B293U1Z2Z0e3z0S0f0L/Screen%20Shot%202013-12-30%20at%205.59.52%20PM.png](http://f.cl.ly/items/3B293U1Z2Z0e3z0S0f0L/Screen%20Shot%202013-12-30%20at%205.59.52%20PM.png)

**Comment by logicalparadox** [comment]
+1 ... even something as simple as:

```
0 tests (0ms)
```

but when you have tests

```
5 tests, 3 passed, 1 failed, 1 pending (3ms)
```
